# this is my Make file I don't know if it works. 

# Variables to control Makefile operations

CXX = g++
CXXFLAGS = -Wall -g

mainProgram: mainProgram.cpp ReplacementSelectionSort.cpp ReplacementSelectionSort.h TournamentSort.h
	$(CXX)	$(CXXFLAGS) -o mainProgram mainProgram.o ReplacementSelectionSort.o TournamentSort.o

